# This workflow will build a package using Maven and publish it to GitHub Packages
# when a release is created or a version tag is pushed.
name: Maven Publish

on:
  release:
    types: [ created ]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build and publish versioned
        run: |
          mvn clean package --file pom.xml
          mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Versioned Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set version to latest and package
        run: |
          mvn versions:set -DnewVersion=latest -DgenerateBackupPoms=false
          mvn clean package --file pom.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish latest to Packages
        run: |
          mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}